apiVersion: apps/v1
kind: Deployment
metadata:
  name: inferno-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inferno-app
  template:
    metadata:
      labels:
        app: inferno-app
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: site-content
          emptyDir: {}
        - name: examplenginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
      initContainers:
      - name: generate-static-files
        image: {{ .Values.inferno.imageUrl }}
        command: ["bundle", "exec", "rake", "web:generate"]
        env:
          - name: TX_SERVER_URL
            value: {{ .Values.inferno.terminologyServer }}
        volumeMounts:
          - name: site-content
            mountPath: /opt/inferno/_site
      - name: run-migrations
        image: {{ .Values.inferno.imageUrl }}
        imagePullPolicy: Always
        command: ["bundle", "exec", "rake", "db:migrate"]
        env:
          - name: TX_SERVER_URL
            value: {{ .Values.inferno.terminologyServer }}
        envFrom:
        - configMapRef:
            name: inferno
        - configMapRef:
            name: postgresql-configmap
        - secretRef:
            name: postgresql-secret
      containers:
      - name: inferno-app
        image: {{ .Values.inferno.imageUrl }}
        imagePullPolicy: Always
        ports:
          - containerPort: 4567
        env:
          - name: TX_SERVER_URL
            value: {{ .Values.inferno.terminologyServer }}
        volumeMounts:
          - name: site-content
            mountPath: /opt/inferno/_site
        envFrom:
        - configMapRef:
            name: inferno
        - configMapRef:
            name: postgresql-configmap
        - secretRef:
            name: postgresql-secret
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
          - name: site-content
            mountPath: /var/www/inferno/public/
          - name: examplenginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf