apiVersion: v1
kind: Service
metadata:
  name: inferno
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 4567
      protocol: TCP
      targetPort: 4567
  selector:
    app: inferno-app
---
apiVersion: v1
kind: Service
metadata:
  name: inferno-redis
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: inferno-redis
---
apiVersion: v1
kind: Service
metadata:
  name: validator-api
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 3500
      protocol: TCP
      targetPort: 3500
  selector:
    app: validator-api
